Fix test job missing token input
betrybe/create-pr-from-files-action pull request #21
Opened 2021-06-11 00:58 UTC by barraponto

🤞

2021-06-11 17:00 UTC, eucleciojosias approved these changes

2021-06-11 18:29 UTC, eucleciojosias requested changes

2021-06-11 18:29 UTC, eucleciojosias commented on .github/workflows/test.yml
> +        token: {{ secrets.GITHUB_TOKEN }}
```suggestion
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

2021-08-18 22:38 UTC, eucleciojosias approved these changes

2021-08-19 19:51 UTC, eucleciojosias commented
@jeanpsv pelo que vi no workflow, nem fazia sentido ter aquele step mais, confere se é ok removê-lo?

2021-08-19 22:07 UTC, jeanpsv approved these changes

2021-08-24 13:32 UTC, merged